// react/todo/src/App.js
import "./App.css";
import "./style.scss";
import { ListComponent } from "./components/list/list";
import { AddNewComponent } from "./components/add/add";
function App() {
  return (
    <div className="App container">
      <ListComponent></ListComponent>
      <AddNewComponent></AddNewComponent>
    </div>
  );
}

export default App;

// angular/todo/src/app/app.component.ts
import { Component } from '@angular/core';
import { Todo } from '../models/todo';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'TODO >. ';


}

<div class="container"><app-list></app-list> <app-add></app-add></div>
